import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Nav from "@/components/nav/nav";
import Footer from "@/components/footer";
import { ClerkProvider } from "@clerk/nextjs";
import { ViewTransitions } from "next-view-transitions";

const inter = Kanit({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<ViewTransitions >
				<html lang="en">
					<body className={`${inter.className} dark overflow-x-hidden `}>
						<main>
							<Nav />
							<div   className="max-w-7xl m-auto">
								{children}
								<Footer />
								<Toaster />
							</div>
						</main>
					</body>
				</html>
			</ViewTransitions>
		</ClerkProvider>
	);
}
